name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
    branches:
      - main
jobs:
  run-tests:
    if: github.event.pull_request.draft == false
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Install
        run: |
          yarn install --no-lockfile
      - name: Lint
        run: yarn lint
